services:
  social_service:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - redis
      - celery
      - celery-beat

  postgres:
    image: postgres:16.0-alpine3.17
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - social_service_db_volume:$PGDATA

  redis:
    image: redis:7.4.0-alpine3.20
    restart: always
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    command: celery -A social_service worker --loglevel=info
    depends_on:
      - redis
    restart: always

  celery-beat:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - ./:/app
    command: celery -A social_service beat --loglevel=info
    depends_on:
      - redis
    restart: always

volumes:
  social_service_db_volume: