# Generated by Django 5.1.2 on 2024-10-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reply",
            field=models.BooleanField(default=False),
        ),
    ]
