# Generated by Django 5.1.2 on 2024-10-25 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_post_reply"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="reply",
            new_name="reply_on_comments",
        ),
    ]
