# Generated by Django 5.1.2 on 2024-10-25 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_rename_reply_post_reply_on_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="reply_time",
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
