# Generated by Django 5.1.2 on 2024-10-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_reply_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reply_on_comments',
            field=models.BooleanField(default=True),
        ),
    ]
