# Generated by Django 5.1.2 on 2024-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0007_alter_post_reply_on_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(max_length=255),
        ),
    ]
