# Generated by Django 5.1.2 on 2024-10-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_alter_comment_options_comment_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
