# Generated by Django 5.1.2 on 2024-10-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(max_length=255),
        ),
    ]
